/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ael.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[9.74, -8.9, -19.05]}>
        <group position={[0.6, 4.32, 25.56]} rotation={[0, -1.57, 0]}>
          <mesh geometry={nodes['profile-gasket'].geometry} material={nodes['profile-gasket'].material} />
          <mesh geometry={nodes['profile-PVC'].geometry} material={nodes['profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.FBA.geometry} material={nodes.FBA.material} position={[0.6, -53.85, 25.82]} rotation={[0, -1.57, 0]} />
        <mesh geometry={nodes.glas.geometry} material={nodes.glas.material} position={[-2.44, 5.47, 24.99]} rotation={[0, -1.57, 0]} />
        <mesh geometry={nodes.beschlag.geometry} material={materials.F9} position={[-1.05, 2.31, 18.3]} rotation={[0, -1.57, 0]} />
      </group>
      <group position={[7.39, 36.47, -20.34]} rotation={[0, 1.57, 0]}>
        <mesh geometry={nodes.Endstab_gasket.geometry} material={materials.rubber} position={[-34.43, -20.98, 2.99]} rotation={[0, -1.57, 0]} />
        <mesh geometry={nodes.Endstab.geometry} material={materials.grey} position={[-34.44, -18.1, 2.99]} rotation={[0, -1.57, 0]} />
        <mesh geometry={nodes.lamellen.geometry} material={materials.grey} position={[-34.43, 0.46, 2.97]} rotation={[0, -1.57, 0]} />
        <mesh geometry={nodes.rf.geometry} material={nodes.rf.material} position={[-34.05, -42.4, 3.03]} rotation={[0, -1.57, 0]} />
        <mesh geometry={nodes.kasten.geometry} material={nodes.kasten.material} position={[-24.54, 26.28, 3.03]} rotation={[0, -1.57, 0]} />
      </group>
      <mesh geometry={nodes.insulation.geometry} material={nodes.insulation.material} position={[-10.38, -37.38, 20.34]} rotation={[0, -1.57, 0]} />
      <mesh geometry={nodes.wall.geometry} material={materials.Concrete} position={[-10.41, -37.38, -2.69]} rotation={[0, -1.57, 0]} />
    </group>
  )
}

useGLTF.preload('/ael.glb')
