/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ct70Rondo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.75, -0.77, 0.96]}>
        <mesh geometry={nodes['profile-PVC'].geometry} material={nodes['profile-PVC'].material} />
        <mesh geometry={nodes['profile-color_inside'].geometry} material={nodes['profile-color_inside'].material} />
        <mesh geometry={nodes['profile-color_outside'].geometry} material={nodes['profile-color_outside'].material} />
      </group>
      <mesh geometry={nodes.hardware.geometry} material={nodes.hardware.material} position={[-0.52, -1.32, 1.51]} />
      <mesh geometry={nodes.gaskets.geometry} material={nodes.gaskets.material} position={[0.06, -0.59, 0.78]} />
      <mesh geometry={nodes.kanteT.geometry} material={nodes.kanteT.material} position={[-0.33, 0.44, -0.25]} />
      <mesh geometry={nodes.kanteB.geometry} material={nodes.kanteB.material} position={[-0.26, 0.26, -0.07]} />
      <mesh geometry={nodes.block.geometry} material={nodes.block.material} position={[-0.28, -0.08, 0.27]} />
      <mesh geometry={nodes.steel.geometry} material={nodes.steel.material} position={[0.09, -1.64, 1.83]} />
      <mesh geometry={nodes.glas.geometry} material={nodes.glas.material} position={[0.01, 1.64, -1.83]} />
    </group>
  )
}

useGLTF.preload('/ct70Rondo.glb')
