/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/k70.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.66, -0.87, 1.18]}>
        <mesh geometry={nodes['profile-PVC'].geometry} material={nodes['profile-PVC'].material} />
        <mesh geometry={nodes['profile-color_inside'].geometry} material={nodes['profile-color_inside'].material} />
        <mesh geometry={nodes['profile-color_outside'].geometry} material={nodes['profile-color_outside'].material} />
      </group>
      <mesh geometry={nodes.gaskets.geometry} material={nodes.gaskets.material} position={[0.32, -0.42, 0.73]} />
      <mesh geometry={nodes.block.geometry} material={nodes.block.material} position={[-0.28, -0.17, 0.49]} />
      <mesh geometry={nodes.steel.geometry} material={nodes.steel.material} position={[-0.03, -1.55, 1.86]} />
      <mesh geometry={nodes.kanteB.geometry} material={nodes.kanteB.material} position={[-0.12, 0.15, 0.17]} />
      <mesh geometry={nodes.kanteT.geometry} material={nodes.kanteT.material} position={[-0.18, 0.31, 0]} />
      <mesh geometry={nodes.hardware.geometry} material={nodes.hardware.material} position={[-0.58, -1.31, 1.62]} />
      <mesh geometry={nodes.glas.geometry} material={nodes.glas.material} position={[0.16, 1.55, -1.86]} />
    </group>
  )
}

useGLTF.preload('/k70.glb')
