/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/k76ad.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.color_outside.geometry}
        material={nodes.color_outside.material}
        position={[1.67, -1.08, 1.15]}
      />
      <mesh
        geometry={nodes.color_inside.geometry}
        material={nodes.color_inside.material}
        position={[-1.67, -0.86, 0.93]}
      />
      <mesh geometry={nodes.profile.geometry} material={nodes.profile.material} position={[0.21, -2.15, 2.21]} />
      <mesh geometry={nodes.steel.geometry} material={nodes.steel.material} position={[0.06, -1.54, 1.61]} />
      <mesh geometry={nodes.gaskets.geometry} material={nodes.gaskets.material} position={[0.27, -0.74, 0.81]} />
      <mesh geometry={nodes.block.geometry} material={nodes.block.material} position={[-0.45, 0, 0.06]} />
      <mesh geometry={nodes.kanteB.geometry} material={nodes.kanteB.material} position={[-0.21, 0.37, -0.31]} />
      <mesh geometry={nodes.kanteT.geometry} material={nodes.kanteT.material} position={[-0.25, 0.52, -0.45]} />
      <mesh geometry={nodes.hardware.geometry} material={nodes.hardware.material} position={[-0.65, -1.11, 1.18]} />
      <mesh geometry={nodes.glas.geometry} material={nodes.glas.material} position={[0, 2.15, -2.21]} />
    </group>
  )
}

useGLTF.preload('/k76ad.glb')
