/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mb86.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.23, -1.75, 1.19]}>
        <mesh geometry={nodes['profile-Aluminium'].geometry} material={materials.Aluminium} />
        <mesh geometry={nodes['profile-color_outside'].geometry} material={materials['color outside']} />
        <mesh geometry={nodes['profile-color_inside'].geometry} material={materials['color inside']} />
      </group>
      <mesh geometry={nodes.gaskets.geometry} material={materials['Rubber - Black']} position={[-0.42, -1.16, 0.54]} />
      <mesh
        geometry={nodes.main_gasket.geometry}
        material={nodes.main_gasket.material}
        position={[0.92, -2.26, 1.64]}
      />
      <mesh geometry={nodes.connectors.geometry} material={nodes.connectors.material} position={[0.67, -2.45, 1.83]} />
      <mesh
        geometry={nodes.block_gasket.geometry}
        material={nodes.block_gasket.material}
        position={[0.65, -0.94, 0.31]}
      />
      <mesh geometry={nodes.kanteT.geometry} material={nodes.kanteT.material} position={[0.64, -0.57, -0.06]} />
      <mesh geometry={nodes.kanteB.geometry} material={nodes.kanteB.material} position={[0.72, -0.69, 0.06]} />
      <mesh geometry={nodes.hardware.geometry} material={nodes.hardware.material} position={[-0.92, -1.96, 1.34]} />
      <mesh geometry={nodes.glas.geometry} material={nodes.glas.material} position={[0.71, 2.45, -1.83]} />
    </group>
  )
}

useGLTF.preload('/mb86.glb')
