/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sk.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[28.5, 43.83, -16.66]}>
        <group position={[-36.1, 12.32, 43.56]}>
          <mesh geometry={nodes.v3lamellen_1.geometry} material={materials['default']} />
          <mesh geometry={nodes['v3lamellen-Mat'].geometry} material={materials.Mat} />
        </group>
        <mesh geometry={nodes.v3alu.geometry} material={nodes.v3alu.material} position={[-36.21, -33.3, 48.79]} />
      </group>
      <group position={[28.5, 43.59, -16.48]}>
        <group position={[-36.36, -39.49, 35.94]}>
          <mesh geometry={nodes['w3profile-gasket'].geometry} material={nodes['w3profile-gasket'].material} />
          <mesh geometry={nodes['w3profile-PVC'].geometry} material={nodes['w3profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.w3FBA.geometry} material={nodes.w3FBA.material} position={[-36.35, -108.66, 36.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w3glas.geometry} material={nodes.w3glas.material} position={[-39.4, -38.35, 35.37]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w3beschlag.geometry} material={materials.F9} position={[-38, -41.5, 28.68]} />
      </group>
      <group position={[28.5, 43.83, -16.66]}>
        <group position={[-36.11, 12.32, 43.56]}>
          <mesh geometry={nodes.v2lamellen_1.geometry} material={materials['default']} />
          <mesh geometry={nodes['v2lamellen-Mat'].geometry} material={materials.Mat} />
        </group>
        <mesh geometry={nodes.v2alu.geometry} material={nodes.v2alu.material} position={[-36.21, -33.3, 48.79]} />
      </group>
      <group position={[7.51, 49.31, -28.43]}>
        <mesh geometry={nodes.steel.geometry} material={nodes.steel.material} position={[-15.35, 15.41, 32.22]} rotation={[Math.PI, -1.57, 0]} />
        <mesh geometry={nodes.verb_1.geometry} material={nodes.verb_1.material} position={[-15.35, 15.76, 33.43]} rotation={[Math.PI, -1.57, 0]} />
        <mesh geometry={nodes.gasket.geometry} material={nodes.gasket.material} position={[-15.31, 9.79, 33.06]} rotation={[Math.PI, -1.57, 0]} />
      </group>
      <group position={[28.5, 43.83, -32.13]}>
        <group position={[-36.11, -3.97, 43.56]}>
          <mesh geometry={nodes.v1lamellen_1.geometry} material={materials['default']} />
          <mesh geometry={nodes['v1lamellen-Mat'].geometry} material={materials.Mat} />
        </group>
        <group position={[-36.11, 13.39, 42.59]}>
          <mesh geometry={nodes.v1lamellen2_1.geometry} material={materials['default']} />
          <mesh geometry={nodes['v1lamellen2-Mat'].geometry} material={materials.Mat} />
        </group>
        <mesh geometry={nodes.v1alu.geometry} material={nodes.v1alu.material} position={[-36.21, -41.44, 48.79]} />
      </group>
      <group position={[28.5, 43.59, -31.96]}>
        <group position={[-36.36, -45.84, 35.94]}>
          <mesh geometry={nodes['w1profile-gasket'].geometry} material={nodes['w1profile-gasket'].material} />
          <mesh geometry={nodes['w1profile-PVC'].geometry} material={nodes['w1profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.w1FBA.geometry} material={nodes.w1FBA.material} position={[-36.35, -108.66, 36.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w1glas.geometry} material={nodes.w1glas.material} position={[-39.4, -44.7, 35.37]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w1beschlag.geometry} material={materials.F9} position={[-38, -47.85, 28.68]} />
      </group>
      <group position={[28.5, 43.59, -31.96]}>
        <group position={[-36.36, -39.92, 35.94]}>
          <mesh geometry={nodes['w2profile-gasket'].geometry} material={nodes['w2profile-gasket'].material} />
          <mesh geometry={nodes['w2profile-PVC'].geometry} material={nodes['w2profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.w2FBA.geometry} material={nodes.w2FBA.material} position={[-36.35, -108.66, 36.2]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w2glas.geometry} material={nodes.w2glas.material} position={[-39.4, -38.78, 35.37]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w2beschlag.geometry} material={materials.F9} position={[-38, -41.93, 28.68]} />
      </group>
      <mesh geometry={nodes.wall.geometry} material={materials.Concrete} position={[-28.5, -39.7, 6.36]} rotation={[0, -1.57, 0]} />
    </group>
  )
}

useGLTF.preload('/sk.glb')
