/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/skp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[16.08, 28.82, -20.48]}>
        <group position={[-19.58, 22.04, 20.41]}>
          <mesh geometry={nodes.v1lamellen_1.geometry} material={materials['default']} />
          <mesh geometry={nodes['v1lamellen-Mat'].geometry} material={materials.Mat} />
        </group>
        <group position={[-19.58, 39.48, 19.44]}>
          <mesh geometry={nodes.v1lamellen2_1.geometry} material={materials['default']} />
          <mesh geometry={nodes['v1lamellen2-Mat'].geometry} material={materials.Mat} />
        </group>
        <group position={[-19.66, -15.24, 25.6]}>
          <mesh geometry={nodes['v1skp_alu-PVC'].geometry} material={nodes['v1skp_alu-PVC'].material} />
          <mesh geometry={nodes['v1skp_alu-weiss'].geometry} material={nodes['v1skp_alu-weiss'].material} />
        </group>
      </group>
      <group position={[16.08, 36.15, -4.34]}>
        <group position={[-19.58, 32.57, 19.49]}>
          <mesh geometry={nodes.v2lamellen_1.geometry} material={materials['default']} />
          <mesh geometry={nodes['v2lamellen-Mat'].geometry} material={materials.Mat} />
        </group>
        <group position={[-19.72, -13.78, 24.81]}>
          <mesh geometry={nodes['v2skp_alu-PVC'].geometry} material={nodes['v2skp_alu-PVC'].material} />
          <mesh geometry={nodes['v2skp_alu-weiss'].geometry} material={nodes['v2skp_alu-weiss'].material} />
        </group>
      </group>
      <group position={[16.08, 28.82, -5]}>
        <group position={[-17.91, 39.9, 20.15]}>
          <mesh geometry={nodes.v3lamellen_1.geometry} material={materials['default']} />
          <mesh geometry={nodes['v3lamellen-Mat'].geometry} material={materials.Mat} />
        </group>
        <group position={[-18.06, -6.45, 25.48]}>
          <mesh geometry={nodes['v3skp_alu-PVC'].geometry} material={nodes['v3skp_alu-PVC'].material} />
          <mesh geometry={nodes['v3skp_alu-weiss'].geometry} material={nodes['v3skp_alu-weiss'].material} />
        </group>
      </group>
      <group position={[-4.92, 34.3, -19.49]}>
        <mesh geometry={nodes.steel.geometry} material={nodes.steel.material} position={[1.18, 41.42, 11.79]} rotation={[Math.PI, -1.57, 0]} />
        <mesh geometry={nodes.verb_1.geometry} material={nodes.verb_1.material} position={[1.18, 41.77, 13]} rotation={[Math.PI, -1.57, 0]} />
        <mesh geometry={nodes.gasket.geometry} material={nodes.gasket.material} position={[1.22, 35.8, 12.64]} rotation={[Math.PI, -1.57, 0]} />
      </group>
      <group position={[16.08, 35.91, -19.64]}>
        <group position={[-19.82, -27.16, 12.14]}>
          <mesh geometry={nodes['w1profile-gasket'].geometry} material={nodes['w1profile-gasket'].material} />
          <mesh geometry={nodes['w1profile-PVC'].geometry} material={nodes['w1profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.w1FBA.geometry} material={nodes.w1FBA.material} position={[-19.82, -89.99, 12.4]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w1glas.geometry} material={nodes.w1glas.material} position={[-22.86, -26.02, 11.56]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w1beschlag.geometry} material={materials.F9} position={[-21.47, -29.17, 4.88]} />
      </group>
      <group position={[16.08, 28.58, -20.3]}>
        <group position={[-19.82, -13.91, 12.8]}>
          <mesh geometry={nodes['w2profile-gasket'].geometry} material={nodes['w2profile-gasket'].material} />
          <mesh geometry={nodes['w2profile-PVC'].geometry} material={nodes['w2profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.w2FBA.geometry} material={nodes.w2FBA.material} position={[-19.82, -82.66, 13.06]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w2glas.geometry} material={nodes.w2glas.material} position={[-22.86, -12.77, 12.23]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w2beschlag.geometry} material={materials.F9} position={[-21.47, -15.92, 5.54]} />
      </group>
      <group position={[16.08, 28.58, -4.82]}>
        <group position={[-18.17, -13.49, 12.63]}>
          <mesh geometry={nodes['w3profile-gasket'].geometry} material={nodes['w3profile-gasket'].material} />
          <mesh geometry={nodes['w3profile-PVC'].geometry} material={nodes['w3profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.w3FBA.geometry} material={nodes.w3FBA.material} position={[-18.16, -82.66, 12.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w3glas.geometry} material={nodes.w3glas.material} position={[-21.21, -12.34, 12.06]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w3beschlag.geometry} material={materials.F9} position={[-19.82, -15.5, 5.37]} />
      </group>
      <mesh geometry={nodes.wall.geometry} material={materials.Concrete} position={[-22.74, -28.7, -5.39]} rotation={[0, -1.57, 0]} />
    </group>
  )
}

useGLTF.preload('/skp.glb')
