/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[20.67, 63.22, -16]}>
        <group position={[-20.54, -39.39, 41.8]}>
          <mesh geometry={nodes['v1alu-PVC'].geometry} material={nodes['v1alu-PVC'].material} />
          <mesh geometry={nodes['v1alu-Iron'].geometry} material={nodes['v1alu-Iron'].material} />
        </group>
        <mesh geometry={nodes.v1lamellen.geometry} material={materials.Mat} position={[-20.44, -4.03, 33.75]} />
      </group>
      <group position={[20.67, 45.12, -33.34]}>
        <group position={[-20.54, -39.39, 41.8]}>
          <mesh geometry={nodes['v2alu-PVC'].geometry} material={nodes['v2alu-PVC'].material} />
          <mesh geometry={nodes['v2alu-Iron'].geometry} material={nodes['v2alu-Iron'].material} />
        </group>
        <mesh geometry={nodes.v2lamellen.geometry} material={materials.Mat} position={[-20.44, -4.03, 33.75]} />
      </group>
      <group position={[-4.34, 5.39, -19.06]}>
        <mesh geometry={nodes.steel.geometry} material={nodes.steel.material} position={[4.51, 62.41, 11.79]} rotation={[Math.PI, -1.57, 0]} />
        <mesh geometry={nodes.verb_1.geometry} material={nodes.verb_1.material} position={[4.51, 62.76, 13]} rotation={[Math.PI, -1.57, 0]} />
        <mesh geometry={nodes.gasket.geometry} material={nodes.gasket.material} position={[4.55, 56.78, 12.64]} rotation={[Math.PI, -1.57, 0]} />
      </group>
      <group position={[16.65, 6.99, -19.2]}>
        <group position={[-16.49, -6.18, 12.14]}>
          <mesh geometry={nodes['w1profile-gasket'].geometry} material={nodes['w1profile-gasket'].material} />
          <mesh geometry={nodes['w1profile-PVC'].geometry} material={nodes['w1profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.w1FBA.geometry} material={nodes.w1FBA.material} position={[-16.49, -69, 12.4]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w1glas.geometry} material={nodes.w1glas.material} position={[-19.53, -5.03, 11.56]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w1beschlag.geometry} material={materials.F9} position={[-18.14, -8.19, 4.88]} />
      </group>
      <group position={[15.11, -0.34, -2.44]}>
        <group position={[-14.84, 7.5, 12.63]}>
          <mesh geometry={nodes['w2profile-gasket'].geometry} material={nodes['w2profile-gasket'].material} />
          <mesh geometry={nodes['w2profile-PVC'].geometry} material={nodes['w2profile-PVC'].material} />
        </group>
        <mesh geometry={nodes.w2FBA.geometry} material={nodes.w2FBA.material} position={[-14.83, -61.67, 12.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w2glas.geometry} material={nodes.w2glas.material} position={[-17.88, 8.64, 12.06]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.w2beschlag.geometry} material={materials.F9} position={[-16.49, 5.49, 5.37]} />
      </group>
      <mesh geometry={nodes.insulation1.geometry} material={nodes.insulation1.material} position={[0.28, 84.01, 33.34]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.insulation2.geometry} material={nodes.insulation2.material} position={[0.19, 65.87, 16.16]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.dg1.geometry} material={nodes.dg1.material} position={[-20.39, -36.44, 26.08]} rotation={[0, -1.57, 0]} />
      <mesh geometry={nodes.dg2.geometry} material={nodes.dg2.material} position={[-20.67, -36.67, 21]} rotation={[0, -1.57, 0]} />
      <mesh geometry={nodes.wall.geometry} material={materials.Concrete} position={[-20.38, -36.63, -3]} rotation={[0, -1.57, 0]} />
    </group>
  )
}

useGLTF.preload('/sp.glb')
