/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wall.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[5.26, 125, 2.62]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes['rks-red'].geometry} material={materials.red} />
        <mesh geometry={nodes['rks-silver'].geometry} material={materials.silver} />
        <mesh geometry={nodes['rks-inside'].geometry} material={materials.inside} />
      </group>
      <group position={[-34.56, -130.83, 13.6]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['fussboden_neu-estrich'].geometry} material={nodes['fussboden_neu-estrich'].material} />
        <mesh geometry={nodes['fussboden_neu-fliesen'].geometry} material={nodes['fussboden_neu-fliesen'].material} />
      </group>
      <group position={[-34.6, -130.83, 13.6]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['fussboden_alt-estrich'].geometry} material={nodes['fussboden_alt-estrich'].material} />
        <mesh geometry={nodes['fussboden_alt-fliesen'].geometry} material={nodes['fussboden_alt-fliesen'].material} />
      </group>
      <group position={[-47.45, 95.57, 7.3]}>
        <mesh geometry={nodes['altkasten-holz1'].geometry} material={materials.holz1} />
        <mesh geometry={nodes['altkasten-holz2'].geometry} material={materials.holz2} />
      </group>
      <group position={[-22.23, -115.95, -1.47]}>
        <mesh geometry={nodes['boden_profil_mit-Glas'].geometry} material={nodes['boden_profil_mit-Glas'].material} />
        <mesh geometry={nodes['boden_profil_mit-hardware'].geometry} material={nodes['boden_profil_mit-hardware'].material} />
        <mesh geometry={nodes['boden_profil_mit-GlasKante'].geometry} material={nodes['boden_profil_mit-GlasKante'].material} />
        <mesh geometry={nodes['boden_profil_mit-WarmeKante'].geometry} material={nodes['boden_profil_mit-WarmeKante'].material} />
        <mesh geometry={nodes['boden_profil_mit-plastic'].geometry} material={nodes['boden_profil_mit-plastic'].material} />
        <mesh geometry={nodes['boden_profil_mit-PVC'].geometry} material={nodes['boden_profil_mit-PVC'].material} />
        <mesh geometry={nodes['boden_profil_mit-aluminium'].geometry} material={nodes['boden_profil_mit-aluminium'].material} />
        <mesh geometry={nodes['boden_profil_mit-Stahl'].geometry} material={nodes['boden_profil_mit-Stahl'].material} />
        <mesh geometry={nodes['boden_profil_mit-gasket'].geometry} material={nodes['boden_profil_mit-gasket'].material} />
        <mesh geometry={nodes['boden_profil_mit-brush'].geometry} material={nodes['boden_profil_mit-brush'].material} />
      </group>
      <group position={[5.21, -14.78, -10.32]}>
        <mesh geometry={nodes['fenster-PVC'].geometry} material={nodes['fenster-PVC'].material} />
        <mesh geometry={nodes['fenster-plastic'].geometry} material={nodes['fenster-plastic'].material} />
        <mesh geometry={nodes['fenster-Glas'].geometry} material={nodes['fenster-Glas'].material} />
        <mesh geometry={nodes['fenster-gasket'].geometry} material={nodes['fenster-gasket'].material} />
      </group>
      <group position={[-5.64, -134.52, -9.19]}>
        <mesh geometry={nodes['boden_profil_ohne-Glas'].geometry} material={nodes['boden_profil_ohne-Glas'].material} />
        <mesh geometry={nodes['boden_profil_ohne-hardware'].geometry} material={nodes['boden_profil_ohne-hardware'].material} />
        <mesh geometry={nodes['boden_profil_ohne-GlasKante'].geometry} material={nodes['boden_profil_ohne-GlasKante'].material} />
        <mesh geometry={nodes['boden_profil_ohne-WarmeKante'].geometry} material={nodes['boden_profil_ohne-WarmeKante'].material} />
        <mesh geometry={nodes['boden_profil_ohne-plastic'].geometry} material={nodes['boden_profil_ohne-plastic'].material} />
        <mesh geometry={nodes['boden_profil_ohne-PVC'].geometry} material={nodes['boden_profil_ohne-PVC'].material} />
        <mesh geometry={nodes['boden_profil_ohne-aluminium'].geometry} material={nodes['boden_profil_ohne-aluminium'].material} />
        <mesh geometry={nodes['boden_profil_ohne-Stahl'].geometry} material={nodes['boden_profil_ohne-Stahl'].material} />
        <mesh geometry={nodes['boden_profil_ohne-gasket'].geometry} material={nodes['boden_profil_ohne-gasket'].material} />
        <mesh geometry={nodes['boden_profil_ohne-brush'].geometry} material={nodes['boden_profil_ohne-brush'].material} />
      </group>
      <mesh geometry={nodes.il_alt_boden_ohne.geometry} material={nodes.il_alt_boden_ohne.material} position={[5.34, -15.58, -5.26]} />
      <mesh geometry={nodes.il_alt_boden_mit.geometry} material={nodes.il_alt_boden_mit.material} position={[5.32, -15.58, 5.93]} />
      <mesh geometry={nodes.il_alt_bruestung_ohne.geometry} material={nodes.il_alt_bruestung_ohne.material} position={[5.24, -15.58, -5.26]} />
      <mesh geometry={nodes.il_alt_bruestung_mit.geometry} material={nodes.il_alt_bruestung_mit.material} position={[5.37, -15.58, 5.93]} />
      <mesh geometry={nodes.mauer_neu_boden_ohne.geometry} material={nodes.mauer_neu_boden_ohne.material} position={[5.14, -15.58, 20.07]} />
      <mesh geometry={nodes.mauer_neu_boden_mit.geometry} material={nodes.mauer_neu_boden_mit.material} position={[5.31, -15.58, 20.07]} />
      <mesh geometry={nodes.mauer_neu_bruestung_ohne.geometry} material={nodes.mauer_neu_bruestung_ohne.material} position={[5.24, -15.58, 20.07]} />
      <mesh geometry={nodes.mauer_neu_bruestung_mit.geometry} material={nodes.mauer_neu_bruestung_mit.material} position={[5.18, -15.58, 20.07]} />
      <mesh geometry={nodes.al_alt_boden.geometry} material={nodes.al_alt_boden.material} position={[5.34, 0, -21.55]} />
      <mesh geometry={nodes.al_alt_bruestung.geometry} material={nodes.al_alt_bruestung.material} position={[5.26, 0, -21.55]} />
      <mesh geometry={nodes.dg_neu_boden.geometry} material={nodes.dg_neu_boden.material} position={[5.42, 0, -21.43]} />
      <mesh geometry={nodes.dg_neu_bruestung.geometry} material={nodes.dg_neu_bruestung.material} position={[5.15, 0, -21.43]} />
      <mesh geometry={nodes.bandmass_neu_bodentief_mit.geometry} material={nodes.bandmass_neu_bodentief_mit.material} position={[8.56, 49.21, 15.73]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.bandmass_neu_bruestung.geometry} material={nodes.bandmass_neu_bruestung.material} position={[1.45, 49.21, 18.47]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.bandmass_bodentief_ohne.geometry} material={nodes.bandmass_bodentief_ohne.material} position={[15.39, 49.21, 7.73]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.bandmass_alt_bruestung.geometry} material={nodes.bandmass_alt_bruestung.material} position={[14.11, 49.21, 2.6]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.bandmass_alt_bodentief_al.geometry} material={nodes.bandmass_alt_bodentief_al.material} position={[-17.44, 49.21, -21.57]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.bandmass_alt_bruestung_mit.geometry} material={nodes.bandmass_alt_bruestung_mit.material} position={[-14.49, 49.21, -21.57]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.bandmass_fussboden.geometry} material={nodes.bandmass_fussboden.material} position={[-16.39, -131.04, 34.62]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.fensterbank.geometry} material={nodes.fensterbank.material} position={[-24.45, -26.49, 3.61]} />
    </group>
  )
}

useGLTF.preload('/wall.glb')
