/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wall.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[15.69, -15.58, 16.95]}>
        <mesh geometry={nodes['il_altbau-mauer'].geometry} material={materials.mauer} />
        <mesh geometry={nodes['il_altbau-outside'].geometry} material={materials.outside} />
      </group>
      <mesh geometry={nodes.alt_spiel.geometry} material={nodes.alt_spiel.material} position={[15.7, 41.59, 5.22]} />
      <mesh geometry={nodes.neu_spiel_R.geometry} material={nodes.neu_spiel_R.material} position={[15.7, 41.59, -9.35]} />
      <mesh geometry={nodes.bandmass_dg.geometry} material={nodes.bandmass_dg.material} position={[15.69, 17.1, -28.41]} />
      <mesh geometry={nodes.bandmass_al.geometry} material={nodes.bandmass_al.material} position={[15.69, 17.1, -11.35]} />
      <mesh geometry={nodes.bandmass_il.geometry} material={nodes.bandmass_il.material} position={[15.69, -15.58, 13.51]} />
      <mesh geometry={nodes.dg_neubau.geometry} material={nodes.dg_neubau.material} position={[15.63, 0, -24.55]} />
      <mesh geometry={nodes.il_neubau.geometry} material={materials.Concrete} position={[15.69, -15.58, 16.95]} />
      <mesh geometry={nodes.putz.geometry} material={nodes.putz.material} position={[15.69, -15.58, 16.95]} />
      <mesh geometry={nodes.al_small.geometry} material={nodes.al_small.material} position={[15.63, 0, -10.54]} />
      <mesh geometry={nodes.al_big.geometry} material={nodes.al_big.material} position={[15.63, 0, -10.54]} />
    </group>
  )
}

useGLTF.preload('/wall.glb')
