/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wall.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-58.52, -27, 4.99]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.FBA.geometry} material={nodes.FBA.material} position={[0.01, 1.84, 0.01]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes.pvc.geometry} material={nodes.pvc.material} position={[58.5, -1.24, -43.56]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.alu.geometry} material={nodes.alu.material} position={[57.67, -5.67, -8.7]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.glas.geometry} material={nodes.glas.material} position={[9.96, -0.86, 40.9]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
      <group position={[-58.52, -27, 0.99]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.FBA_1.geometry} material={nodes.FBA_1.material} position={[0.02, 1.83, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
        <mesh geometry={nodes.pvc_1.geometry} material={nodes.pvc_1.material} position={[58.52, -1.24, -33.21]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.alu_1.geometry} material={nodes.alu_1.material} position={[57.69, -5.67, -0.04]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.glas_1.geometry} material={nodes.glas_1.material} position={[9.97, -0.87, 40.89]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
      </group>
      <group position={[58.53, 111, -1]}>
        <mesh geometry={nodes.Endstab_gasket.geometry} material={nodes.Endstab_gasket.material} position={[-34.45, -58.18, 9.61]} />
        <mesh geometry={nodes.Endstab.geometry} material={nodes.Endstab.material} position={[-34.45, -58.18, 9.61]} />
        <mesh geometry={nodes.lamelle7.geometry} material={nodes.lamelle7.material} position={[-19.42, -50.57, 9.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lamelle6.geometry} material={nodes.lamelle6.material} position={[-19.42, -46.57, 9.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lamelle5.geometry} material={nodes.lamelle5.material} position={[-19.42, -38.59, 9.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lamelle4.geometry} material={nodes.lamelle4.material} position={[-19.42, -42.59, 9.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lamelle3.geometry} material={nodes.lamelle3.material} position={[-19.42, -34.61, 9.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lamelle2.geometry} material={nodes.lamelle2.material} position={[-19.42, -30.61, 9.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lamelle1.geometry} material={nodes.lamelle1.material} position={[-19.42, -26.56, 9.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.lamelle.geometry} material={nodes.lamelle.material} position={[-19.42, -22.58, 9.89]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.rfR.geometry} material={nodes.rfR.material} position={[-117, -21.01, 11.51]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.rfL.geometry} material={nodes.rfL.material} position={[-6, -21.01, 9.51]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} />
        <mesh geometry={nodes.boczekL.geometry} material={nodes.boczekL.material} position={[0, -21.01, 0]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.kasten.geometry} material={nodes.kasten.material} position={[-116, -21.51, 11.51]} />
        <mesh geometry={nodes.boczekR.geometry} material={nodes.boczekR.material} position={[-117, -21.01, 11.51]} rotation={[0, 1.57, 0]} />
      </group>
      <group position={[0, 0, 11]}>
        <mesh geometry={nodes['IL_altbau_bruestung21-plaster'].geometry} material={nodes['IL_altbau_bruestung21-plaster'].material} />
        <mesh geometry={nodes['IL_altbau_bruestung21-wall'].geometry} material={materials.wall} />
        <mesh geometry={nodes['IL_altbau_bruestung21-outside'].geometry} material={materials.outside} />
        <mesh geometry={nodes['IL_altbau_bruestung21-inside'].geometry} material={materials.inside} />
      </group>
      <mesh geometry={nodes.al_bez_male_niskie.geometry} material={nodes.al_bez_male_niskie.material} position={[0, 0, 17]} />
      <mesh geometry={nodes.al_rol_duze_niskie1.geometry} material={nodes.al_rol_duze_niskie1.material} position={[0, 0, 17]} />
    </group>
  )
}

useGLTF.preload('/wall.glb')
